# Generated by Django 5.2.7 on 2025-10-30 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_invitation"),
    ]

    operations = []
